name: Build

on:
  push:
    branches:
      - main
    paths:
      - "go.mod"
      - "go.sum"
      - "**/*.go"
      - "Dockerfile"
      - ".github/workflows/build.yml"
  pull_request:
    paths:
      - "go.mod"
      - "go.sum"
      - "**/*.go"
      - "Dockerfile"
      - ".github/workflows/build.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.mod'

      - name: Run tests
        run: |
          go test ./... -v

      # Note that the tag is actually only used for pushing images from the
      # default branch. In the PR context it's generated for debugging
      # purposes.
      - name: Calculate tag
        id: calculate-main-tag
        run: |
          SHA=$(git rev-parse --short HEAD)
          echo "tag=main-$(date +'%Y-%m-%d')-${SHA}" | tee -a "${GITHUB_OUTPUT}"

      - id: push-to-gar
        uses: grafana/shared-workflows/actions/push-to-gar-docker@cb554367777b86e817f51da741a8be143f3582dc
        with:
          tags: |-
            type=raw,value=latest
            type=raw,enable={{is_default_branch}},value=${{ steps.calculate-main-tag.outputs.tag }}
          platforms: linux/amd64${{ github.event_name == 'push' && ',linux/arm64' || ''}}
          image_name: "github-rate-limit-prometheus-exporter"
          environment: ${{ github.event_name == 'pull_request' && 'dev' || 'prod' }}
          push: ${{ github.event_name != 'pull_request' }}
          build-args: "version=${{ steps.calculate-main-tag.outputs.tag }}"
