name: Build

on:
  push:
    branches:
      - master
    paths:
      - "go.mod"
      - "go.sum"
      - "**/*.go"
      - "Dockerfile"
      - ".github/workflows/build.yml"
  pull_request:
    paths:
      - "go.mod"
      - "go.sum"
      - "**/*.go"
      - "Dockerfile"
      - ".github/workflows/build.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false

      - id: push-to-gar
        uses: grafana/shared-workflows/actions/push-to-gar-docker@cb554367777b86e817f51da741a8be143f3582dc
        with:
          tags: |-
            type=raw,value=latest
            type=sha,format=long,prefix={{branch}}-,enable=${{ github.event_name == 'push' && 'true' || 'false' }}
          platforms: linux/amd64${{ github.event_name == 'push' && ',linux/arm64' || ''}}
          image_name: "github-rate-limit-prometheus-exporter"
          environment: ${{ github.event_name == 'pull_request' && 'dev' || 'prod' }}
          push: ${{ github.event_name != 'pull_request' }}
